Repository CodeConnoisseur74/team7-grogu-23-hackathon, pull requests merged in 2023-05, with the labels that each got.

#49 Hero js features
  assets/css/hero-test.css
  assets/images/r2-d2.png
  assets/images/rey.png
  assets/js/game-hero.js
  hero-test.html
Labels: task

#66 My new feature
  assets/css/style.css
  game.html
Labels: invalid

#73 Hero js features and main.html modals
  assets/css/modal-style.css
  assets/images/darth-maul.png
  assets/images/emperor-palpatin.png
  assets/images/general-grievous.png
  assets/images/rey.png
  assets/js/game-hero.js
  game.html
  hero-test.html
Labels: task

#99 Krystal
  README.md
  assets/css/style.css
  assets/css/villain-test.css
  game.html
  villian-test.html
Labels: help wanted

#117 My new feature
  game.html
Labels: task

#133 add div to display alert message
  assets/css/style.css
  game.html
Labels: task

#136 Refactor rewards functions
  assets/js/game-hero.js
  assets/js/game-setup.js
  game.html
Labels: task
